name: Dart CI

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Get dependencies
        run: flutter pub get
      - name: Flutter Format
        run: dart format --set-exit-if-changed .