name: Dart CI

on:
  push:
    branches:
      - master  # Cambia esto si tu rama principal tiene otro nombre
  pull_request:
    branches:
      - master  # Cambia esto si tu rama principal tiene otro nombre

jobs:        
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable  # Usa la versión estable de Dart
      - name: Get dependencies
        run: dart pub get
      - name: Dart Analyze
        run: dart analyze

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Dart Format
        run: dart format --set-exit-if-changed .
