name: Dart CI

on:
  push:
    branches:
      - master  # Cambia esto si tu rama principal tiene otro nombre
  pull_request:
    branches:
      - master  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Get dependencies
        run: flutter pub get
      - name: Dart Analyze
        run: flutter analyze

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Get dependencies
        run: flutter pub get
      - name: Dart Analyze
        run: flutter analyze
